### ISSUE TITLE
token

### ISSUE THREAD

**Issue by WhiteHodok** [NBernkastel/ML_TEST2#1]
Почему у тебя токен в открытом доступе ? 

![image](https://github.com/NBernkastel/ML_TEST2/assets/39564937/086ca824-282f-4a13-b979-29b652603908)

Его нельзя через .env подгрузить?

**Comment by NBernkastel** [comment]
А в чем разница если мне всё равно тут нужно было его оставить

**Comment by WhiteHodok** [comment]
он типо общедосутпный?

**Comment by NBernkastel** [comment]
это тестовое задание
